#!/bin/bash
#
# run this in top level install directory
#
test -d Src || { echo 'Please run in top-level install directory'; exit 1; }

MODELDIR=`pwd`/models
#
# Let python known where the modules are found:
PYTHONPATH=`pwd`/Src:`pwd`/lib/python; export PYTHONPATH
echo PYTHONPATH is $PYTHONPATH
#
echo "model directory? [$MODELDIR]"
read ANS
if [ z$ANS != z ]
then
	MODELDIR=$ANS
fi

# if MODELDIR exists, offer to destroy it
if [ -d $MODELDIR ];
then
# destroy any existing models in the model directory
	echo "Remove models in $MODELDIR? [N]"
	read ANS
	if [ z$ANS == zY ]
	then
		rm -rf $MODELDIR
	fi
fi

# if MODELDIR was destroyed, or we never had one, create and
# populate it
if [ ! -e $MODELDIR ];
then
	echo "Creating model 'James', username 'james', password 'secret'"
	mkdir -p $MODELDIR
	rm -f output_* error_output*
	python Src/Utils/mkmodel.py Src/Modeldefs/user $MODELDIR James:james:secret > output_james 2> error_output_james

#
# Check the files that have been made in the models directory
	du -a $MODELDIR

#
# Check the size of the output and error files
	ls -l output* 
	more output*
	ls -l error*
	more error*
fi

#
# Run the Base tests
test -s $HOME/.personis_server.conf || cp Src/personis_serverDEV.conf $HOME/.personis_server.conf
test -s $HOME/.personis.conf || cp Src/personisDEV.conf $HOME/.personis.conf
echo "Setup complete."
