application: personisae
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /icon.gif
  static_files: static/images/Personis_icon.gif
  upload: static/images/Personis_icon.gif

- url: /.*
  script: gae_server.app
  login: required

libraries:
- name: django
  version: "1.2"

