[global]
server.socket_port: 2005
server.socket_host = 'enterprise.it.usyd.edu.au'
server.threadpool: 10
server.environment: "development"
#autoreload.on = False
server.showTracebacks: True
server.logToScreen: True
log.error_file: 'site.log'
log.screen: True

[/favicon.ico]
tools.etags.on = True
tools.staticfile.on = True
tools.staticfile.filename = "/home/jbu/personis/personis/server/static/images/favicon.ico"

[/static]
tools.etags.on = True
tools.staticdir.on = True
tools.gzip.on: True
tools.gzip.mime_types: ['text/html', 'text/plain', 'application/json', 'text/javascript', 'application/javascript']
tools.staticdir.dir = "/home/jbu/personis/personis/server/static"

[/doc]
tools.etags.on = True
tools.staticdir.on = True
tools.gzip.on: True
tools.gzip.mime_types: ['text/html', 'text/plain', 'application/json', 'text/javascript', 'application/javascript']
tools.staticdir.dir = "/home/jbu/personis/personis/doc/_build/html"

[/]
#tools.encode.on: False
#tools.gzip.on: True
#tools.gzip.mime_types: ['text/html', 'text/plain', 'application/json', 'text/javascript', 'application/javascript']
tools.sessions.on: True

