#!/bin/bash
#
# run this in install directory
#
test -d Tests || { echo 'Please run in top-level install directory'; exit 1; }

MODELDIR=`pwd`/Tests/Models
#
# Let python known where the modules are found:
PYTHONPATH=`pwd`/Src:`pwd`/lib/python; export PYTHONPATH
echo PYTHONPATH is $PYTHONPATH
#
echo "model directory? [$MODELDIR]"
read ANS
if [ z$ANS != z ]
then
        MODELDIR=$ANS
fi
# destroy any existing models in the model directory
echo "Remove models in $MODELDIR? [N]"
read ANS
if [ z$ANS == zY ]
then
        rm -rf $MODELDIR
        mkdir -p $MODELDIR
	echo "creating model 'Alice', username 'alice', password 'secret'"
	python Src/Utils/mkmodel.py Src/Modeldefs/user $MODELDIR alice:alice:pass1 > output_alice 2> error_output_alice
#
# Check the files that have been made in the models directory
	du -a $MODELDIR
#
# Check the size of the output and error files
	ls -l output* 
	ls -l error*
fi

#
# Run the Server tests
#test -s $HOME/.personis_server.conf || cp Src/personis_serverDEV.conf $HOME/.personis_server.conf
#test -s $HOME/.personis.conf || cp Src/personisDEV.conf $HOME/.personis.conf
echo 'killing old server processes (killall python)'
killall python
killall Python   # for the Mac.....
echo Starting server...
python Src/Personis.py -c Src/personis_server.conf --models $MODELDIR &
sleep 5
echo "Server running. No run some tests!"
