application: personislog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/image/favicon.ico
  upload: static/image/favicon\.ico

- url: /static
  static_dir: static

- url: /image/(.*\.(gif|png|jpg|ico))
  static_files: static/image/\1
  upload: static/image/(.*\.(gif|png|jpg|ico))

- url: /.*
  script: log-llum.app
